/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:53b04e6c-66e8-4f80-9635-c32c784d9db1",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_U62wqdkVD",
    "aws_user_pools_web_client_id": "5rqlj3da1766rtuaoba758ih3n",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://tq7uvykyhbfwzbxpfnuiengpxi.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
